version: "3.9"
services:
  api:
    environment:
      - WORKDIR=/repo/
    expose:
      - "8000"
    ports:
      - "8000:8000"
    image: lmoss/neural-rock:latest
    command: uvicorn api:app --reload --app-dir /repo/api --host 0.0.0.0 --port 8000
    restart: always
  viewer:
    environment:
      - WORKDIR=/repo/
      - APIHOST=api
    expose:
      - "80"
    ports:
      - "80:80"
    image: lmoss/neural-rock:latest
    depends_on:
      - api
    command: python -m panel serve /repo/viewer/viewer.py --allow-websocket-origin="*" --port 80
    restart: always