name: neural_rock
channels:
  - pyviz
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - pytest
  - pytorch
  - torchvision
  - cudatoolkit=10.1
  - scipy
  - tensorboard
  - matplotlib
  - nb_conda_kernels
  - h5py
  - scikit-learn
  - bokeh
  - panel
  - holoviews
  - datashader
  - pip:
    - tqdm
    - notebook
    - streamlit
    - captum
    - wandb
    - imageio
    - albumentations
    - xlrd
    - pytorch_lightning