vpc_cidr_block = "10.0.0.0/16"
subnet_cidr_block = "10.0.10.0/24"
avail_zone = "eu-west-1a"
env_prefix = "dev"
instance_type = "t3.large"
public_key_location = "/home/lmoss/.ssh/discovery_deploy.pub"
private_key_location = "/home/lmoss/.ssh/discovery_deploy"